import json

notebook = {
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# RELDEC Results Dashboard\n",
    "Below you will find both the static overview plots and an interactive widget to filter methods dynamically."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "import ipywidgets as widgets\n",
    "from ipywidgets import interact\n",
    "import numpy as np\n",
    "from pathlib import Path\n",
    "%matplotlib inline\n",
    "\n",
    "ROOT = Path('/root/Research/RithvikDecoder/Decoder')\n",
    "\n",
    "def read_rithvik_csv(path, code_default, method_default):\n",
    "    df = pd.read_csv(path)\n",
    "    if 'method' not in df.columns: df['method'] = method_default\n",
    "    if 'ber' not in df.columns: df['ber'] = 0.0\n",
    "    if 'success_rate' in df.columns:\n",
    "        df['fer'] = 1.0 - df['success_rate']\n",
    "    elif 'fer' not in df.columns:\n",
    "        df['fer'] = 0.0\n",
    "    if 'avg_iters' in df.columns:\n",
    "        df['avg_messages'] = df['avg_iters'] * (576 if 'mackay' in code_default.lower() else 2456)\n",
    "    elif 'avg_messages' not in df.columns:\n",
    "        df['avg_messages'] = np.nan\n",
    "    df['code'] = code_default\n",
    "    df['frames'] = 1000\n",
    "    return df\n",
    "\n",
    "all_dfs = []\n",
    "for p in [ROOT/'RELDEC'/'algorithms'/'results', ROOT/'RELDEC'/'results', ROOT/'tmp_exports'/'rithvik']:\n",
    "    if not p.exists(): continue\n",
    "    for file in p.rglob('*.csv'):\n",
    "        try:\n",
    "            if 'ppo_mackay' in file.name: all_dfs.append(read_rithvik_csv(file, 'mackay', 'ppo'))\n",
    "            elif 'ppo_mi_wran' in file.name: all_dfs.append(read_rithvik_csv(file, 'wran', 'ppo_mi'))\n",
    "            else:\n",
    "                df = pd.read_csv(file)\n",
    "                if 'method' not in df.columns or 'snr_db' not in df.columns: continue\n",
    "                if 'frames' in df.columns: df = df[df['frames'] >= 30]\n",
    "                if 'matrix_csv' in df.columns:\n",
    "                    df['code'] = np.where(df['matrix_csv'].str.lower().str.contains('wran'), 'wran', \n",
    "                                 np.where(df['matrix_csv'].str.lower().str.contains('mackay'), 'mackay', 'other'))\n",
    "                all_dfs.append(df)\n",
    "        except: pass\n",
    "\n",
    "if all_dfs:\n",
    "    data = pd.concat(all_dfs, ignore_index=True)\n",
    "    if 'frames' in data.columns:\n",
    "        data = data.sort_values('frames', ascending=False).drop_duplicates(subset=['code', 'method', 'snr_db'])\n",
    "else:\n",
    "    data = pd.DataFrame(columns=['code', 'method', 'snr_db', 'ber', 'fer', 'avg_messages'])\n",
    "\n",
    "methods_available = sorted(data['method'].dropna().unique())\n",
    "colors = plt.cm.tab20.colors\n",
    "cmap = {m: colors[i % len(colors)] for i, m in enumerate(methods_available)}\n",
    "\n",
    "print(f\"Loaded {len(data)} rows of data successfully!\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 2. Static Plots (Guaranteed to render)\n",
    "def plot_static(matrix_name):\n",
    "    df = data[data['code'] == matrix_name]\n",
    "    if df.empty: return\n",
    "    \n",
    "    fig, axes = plt.subplots(1, 3, figsize=(18, 5))\n",
    "    fig.suptitle(f\"{matrix_name.upper()} Combined Results\", fontsize=14, fontweight=\"bold\")\n",
    "    metrics = [('ber', 'BER', True), ('fer', 'FER', True), ('avg_messages', 'Avg Messages', False)]\n",
    "    \n",
    "    for ax, (col, title, logy) in zip(axes, metrics):\n",
    "        for method in methods_available:\n",
    "            m_df = df[df['method'] == method].sort_values('snr_db')\n",
    "            ys = m_df[col].dropna()\n",
    "            if len(ys) == 0: continue\n",
    "            if (ys == 0).all() and logy: continue\n",
    "            ax.plot(m_df.loc[ys.index, 'snr_db'], ys, marker='o', label=method, color=cmap[method])\n",
    "            \n",
    "        ax.set_title(title)\n",
    "        ax.set_xlabel('SNR (dB)')\n",
    "        ax.grid(True, alpha=0.3)\n",
    "        if logy: ax.set_yscale('log')\n",
    "        ax.legend(fontsize=8)\n",
    "    plt.tight_layout()\n",
    "    plt.show()\n",
    "\n",
    "plot_static('wran')\n",
    "plot_static('mackay')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 3. Interactive Filter Dashboard\n",
    "min_snr, max_snr = float(data['snr_db'].min()) if len(data) else 0.0, float(data['snr_db'].max()) if len(data) else 10.0\n",
    "\n",
    "def interactive_dashboard(Matrix, Methods, Min_SNR, Max_SNR):\n",
    "    if not Methods: return print(\"Please select at least one method.\")\n",
    "    df = data[(data['code'] == Matrix) & (data['method'].isin(Methods)) & \n",
    "              (data['snr_db'] >= Min_SNR) & (data['snr_db'] <= Max_SNR)]\n",
    "    if df.empty: return print(\"No data available for these filters.\")\n",
    "        \n",
    "    fig, axes = plt.subplots(1, 3, figsize=(18, 5))\n",
    "    for ax, (col, title, logy) in zip(axes, [('ber', 'BER', True), ('fer', 'FER', True), ('avg_messages', 'Avg Messages', False)]):\n",
    "        for method in Methods:\n",
    "            m_df = df[df['method'] == method].sort_values('snr_db')\n",
    "            ys = m_df[col].dropna()\n",
    "            if len(ys) == 0 or ((ys == 0).all() and logy): continue\n",
    "            ax.plot(m_df.loc[ys.index, 'snr_db'], ys, marker='o', label=method, color=cmap[method])\n",
    "        ax.set_title(title)\n",
    "        ax.grid(True, alpha=0.3)\n",
    "        if logy: ax.set_yscale('log')\n",
    "        ax.legend(fontsize=8)\n",
    "    plt.tight_layout()\n",
    "    plt.show()\n",
    "\n",
    "interact(interactive_dashboard, \n",
    "         Matrix=widgets.Dropdown(options=['wran', 'mackay'], value='wran'),\n",
    "         Methods=widgets.SelectMultiple(options=methods_available, value=tuple(methods_available), rows=8),\n",
    "         Min_SNR=widgets.FloatSlider(value=min_snr, min=min_snr, max=max_snr, step=0.5),\n",
    "         Max_SNR=widgets.FloatSlider(value=max_snr, min=min_snr, max=max_snr, step=0.5));"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {"name": "ipython", "version": 3},\n",
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}

with open("tmp_exports/interactive_dashboard.ipynb", "w") as f:
    json.dump(notebook, f, indent=1)
