benchmarking:
  flooding_only_z1: true
  methods:
    - flooding
    - round_robin
    - reldec
    - reldec_misq_global
    - tabular_augmented_max_avg_zx
  train:
    tabular:
      episodes_per_snr: 2
    deep:
      episodes_per_snr: 0
  evaluation:
    snr_db: [1.0, 1.5, 2.0, 2.5, 3.0]
    episodes_per_snr: 2
    target_frame_errors: 300
    max_frames: 100
parameters:
  mi_bins: 4
system:
  gpu_workers: 4
  cpu_workers: 40
  seed: 42
